// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbaApi.Models;

namespace NbaApi.Migrations
{
    [DbContext(typeof(NbaContext))]
    partial class NbaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("NbaApi.Models.NbaClub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClubCity");

                    b.Property<string>("ClubName");

                    b.Property<float>("FGA");

                    b.Property<float>("FGM");

                    b.Property<int>("GP");

                    b.Property<float>("MIN");

                    b.Property<float>("PTS");

                    b.HasKey("Id");

                    b.ToTable("NbaClubs");
                });

            modelBuilder.Entity("NbaApi.Models.NbaPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ClubId");

                    b.Property<float>("FGA");

                    b.Property<float>("FGM");

                    b.Property<string>("Firstname");

                    b.Property<int>("GP");

                    b.Property<string>("Lastname");

                    b.Property<float>("MIN");

                    b.Property<int>("Number");

                    b.Property<float>("PTS");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("NbaPlayers");
                });

            modelBuilder.Entity("NbaApi.Models.NbaPlayer", b =>
                {
                    b.HasOne("NbaApi.Models.NbaClub", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
